# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:15
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u4f1a\u8bae\u6807\u9898')),
                ('start_time', models.DateTimeField(blank=True)),
                ('content_A', DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u8bae\u7a0b')),
                ('content_B', DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u7eaa\u8981')),
                ('content_C', DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u4e0b\u4e00\u6b65\u5de5\u4f5c\u5b89\u6392')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('modified_save', models.DateTimeField(blank=True, null=True, verbose_name='\u6700\u540e\u624b\u52a8\u4fdd\u5b58\u65f6\u95f4')),
                ('content_A_save', models.TextField(blank=True, verbose_name='\u8bae\u7a0b\uff08\u624b\u52a8\u4fdd\u5b58\uff09')),
                ('content_B_save', models.TextField(blank=True, verbose_name='\u7eaa\u8981\uff08\u624b\u52a8\u4fdd\u5b58\uff09')),
                ('content_C_save', models.TextField(blank=True, verbose_name='\u4e0b\u4e00\u6b65\u5de5\u4f5c\u5b89\u6392\uff08\u624b\u52a8\u4fdd\u5b58\uff09')),
                ('attendees', models.ManyToManyField(related_name='attended_entries', to=settings.AUTH_USER_MODEL, verbose_name='\u53c2\u4f1a\u4eba')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_entries', to=settings.AUTH_USER_MODEL, verbose_name='\u4f1a\u8bae\u7eaa\u8981\u521b\u5efa\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u59d3\u540d')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90e8\u95e8')),
                ('wx_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5fae\u4fe1')),
            ],
        ),
    ]
