# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='end_time',
            field=models.DateTimeField(blank=True, default='2016-07-10'),
            preserve_default=False,
        ),
    ]
