# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0004_auto_20160927_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minutes.Entry'),
            preserve_default=False,
        ),
    ]
