# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0005_profile_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='entry',
        ),
        migrations.AddField(
            model_name='profile',
            name='entry',
            field=models.ManyToManyField(to='minutes.Entry'),
        ),
    ]
