# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0006_auto_20161004_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='entry',
        ),
        migrations.AddField(
            model_name='profile',
            name='attended_entries',
            field=models.ManyToManyField(related_name='attendee', to='minutes.Entry', verbose_name='\u51fa\u5e2d\u7684\u4f1a\u8bae'),
        ),
    ]
