# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0009_auto_20161018_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attended_entries',
            field=models.ManyToManyField(to='minutes.Entry'),
        ),
    ]
