# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0011_auto_20161018_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attended_entries',
            field=models.ManyToManyField(related_name='attendee', to='minutes.Entry', verbose_name='\u51fa\u5e2d\u7684\u4f1a\u8bae'),
        ),
    ]
