# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0017_auto_20161018_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='attendees',
            new_name='attendees_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='entry',
            field=models.ManyToManyField(related_name='attendees', to='minutes.Entry', verbose_name='\u51fa\u5e2d\u7684\u4f1a\u8bae'),
        ),
    ]
