# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0018_auto_20161018_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='entry',
            new_name='entries',
        ),
    ]
