# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20160424_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='nationality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='assigned_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='assigned_nationality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
