# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20160604_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewtoprovider',
            options={'verbose_name': 'ReviewToProvider', 'verbose_name_plural': 'ReviewToProviders'},
        ),
    ]
