# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170205_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='Dtime',
            new_name='created',
        ),
    ]
