# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170206_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
    ]
