# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_log_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='character',
            field=models.IntegerField(blank=True, choices=[(0, b'buyer'), (1, b'provider')], null=True),
        ),
    ]
