# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20170206_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='type',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='source',
            new_name='client',
        ),
    ]
