# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20170206_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sku_topic_buyer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
