# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20170208_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sku_topic',
            new_name='skus_topic',
        ),
    ]
